In [0]:
import pandas as pd

In [19]:
df = pd.read_csv('/content/train.csv')
del df['id']
df

species   margin1   margin2  ...  texture62  texture63  texture64
0              Acer_Opalus  0.007812  0.023438  ...   0.004883   0.000000   0.025391
1    Pterocarya_Stenoptera  0.005859  0.000000  ...   0.000977   0.039062   0.022461
2     Quercus_Hartwissiana  0.005859  0.009766  ...   0.000000   0.020508   0.002930
3          Tilia_Tomentosa  0.000000  0.003906  ...   0.017578   0.000000   0.047852
4       Quercus_Variabilis  0.005859  0.003906  ...   0.000000   0.000000   0.031250
..                     ...       ...       ...  ...        ...        ...        ...
985   Magnolia_Salicifolia  0.060547  0.119140  ...   0.000000   0.000000   0.018555
986            Acer_Pictum  0.001953  0.003906  ...   0.000977   0.000000   0.021484
987     Alnus_Maximowiczii  0.001953  0.003906  ...   0.027344   0.000000   0.001953
988          Quercus_Rubra  0.000000  0.000000  ...   0.000000   0.001953   0.002930
989         Quercus_Afares  0.023438  0.019531  ...   0.023438   0.025391   0.022461

[990 rows x 193 columns]

In [69]:
df.describe()

species     margin1     margin2  ...   texture62   texture63   texture64
count  990.000000  990.000000  990.000000  ...  990.000000  990.000000  990.000000
mean    49.000000    0.017412    0.028539  ...    0.020291    0.008989    0.019420
std     28.591824    0.019739    0.038855  ...    0.039040    0.013791    0.022768
min      0.000000    0.000000    0.000000  ...    0.000000    0.000000    0.000000
25%     24.000000    0.001953    0.001953  ...    0.000000    0.000000    0.000977
50%     49.000000    0.009766    0.011719  ...    0.003906    0.002930    0.011719
75%     74.000000    0.025391    0.041016  ...    0.023438    0.012695    0.029297
max     98.000000    0.087891    0.205080  ...    0.375980    0.086914    0.141600

[8 rows x 193 columns]

In [20]:
df['species'].value_counts()

Quercus_Rubra             10
Tilia_Platyphyllos        10
Arundinaria_Simonii       10
Quercus_Phellos           10
Quercus_x_Hispanica       10
                          ..
Alnus_Rubra               10
Quercus_Semecarpifolia    10
Acer_Palmatum             10
Cornus_Chinensis          10
Acer_Opalus               10
Name: species, Length: 99, dtype: int64

-As we can see from above result given dataset in perfectly balanced

In [0]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit(df['species'])
encoded_values = le.transform(df['species'])
encoded_values

In [60]:
le.classes_

99

In [22]:
df['species']= encoded_values
df.shape

(990, 193)

In [0]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn import svm

In [0]:
X = df.iloc[:,1:193]
y = df.iloc[:,0]

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [35]:
rf_clf = RandomForestClassifier(random_state=0)
rf_clf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [43]:
y_pred_rf = rf_clf.predict(X_test)
y_pred_rf

array([ 5, 92,  5,  9, 33, 52, 17, 76, 20, 61, 78, 52, 36, 20, 52, 39, 95,
       33, 52, 11, 17, 75, 60, 39, 74, 72, 13, 10, 40, 41, 58, 76, 52,  5,
       89, 72, 26, 55, 89, 38, 48, 66, 34, 48, 98, 67, 89, 83, 91, 43, 81,
       80, 15, 34, 22, 53, 30, 37, 78, 49, 70, 45, 21, 32, 65, 60, 27, 25,
       98, 20, 83, 32, 19, 45, 59, 67, 41, 66, 40, 97, 79, 85, 92, 50, 85,
       54, 45, 54, 93,  9, 19, 45, 95, 71, 88, 64, 97, 26, 65, 73,  9, 25,
       18, 96, 11, 17, 90, 75, 46, 66, 67, 21, 33, 32, 40, 85, 36, 78, 10,
       28,  2,  6, 72, 35, 23, 60, 91, 46, 97, 73, 26, 74, 26, 14, 40, 59,
       55, 27, 80, 82, 16, 12, 62,  0, 41, 29, 34, 44, 44, 56, 48, 44, 14,
       24, 51, 15, 89, 28, 66, 45, 75, 52, 11, 61, 27, 10, 44, 51, 63, 29,
       93, 67, 56, 36, 82, 35, 65, 71, 47, 54, 31, 20, 98, 49, 41, 28, 43,
       92, 66, 82, 33, 53, 91, 13, 37,  2, 66, 35])

In [36]:
dt_clf = DecisionTreeClassifier(random_state=0)
dt_clf.fit(X_train, y_train)


DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=0, splitter='best')

In [44]:
y_pred_dt = dt_clf.predict(X_test)
y_pred_dt

array([92, 73,  5,  8, 32,  6,  7, 76,  9, 61, 78, 52, 79, 20, 68, 39, 95,
       33, 68, 98, 17, 56, 60, 39, 74, 72, 13, 55, 40,  3, 58, 23, 58, 75,
       89, 72, 22, 55, 24, 38, 48, 62, 87, 41, 53, 67, 24, 42, 10, 96, 45,
       80, 15, 85, 22, 54, 30, 37, 78, 13, 70, 45, 42, 33, 25, 60, 27, 25,
       68, 20, 84, 33, 19, 45, 59, 67, 32, 97, 36, 62, 79, 58, 92, 68, 34,
       65, 34, 98, 93,  8, 94, 45, 95, 71, 88, 64,  9, 16, 65, 73,  9, 62,
       18, 96, 11, 17, 90, 75, 51, 42, 67, 88, 10, 32, 39, 85, 25, 78, 10,
       28,  2,  6, 22, 35, 23, 60, 91, 46, 97, 86, 22, 74, 22, 14, 67, 59,
       55, 66, 80, 82, 84, 86, 79,  0, 94, 29, 34, 66, 62, 66, 48, 44, 14,
        9, 51, 15, 58, 28, 66, 34, 56, 52, 11, 61, 66, 10, 62, 51, 59, 29,
       93, 34, 56, 34, 82, 40, 25, 71, 47, 54, 31, 20, 98, 49, 41, 28, 43,
       10, 66, 82, 33, 65, 91, 98, 37, 38, 66, 35])

In [37]:
svm_clf = svm.SVC()
svm_clf.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [45]:
y_pred_svm = svm_clf.predict(X_test)
y_pred_svm

array([ 5, 73,  5,  9, 33, 83,  7, 76, 20, 61, 78, 83, 36, 20, 52, 39, 95,
       33, 83, 11, 17, 86, 60, 39, 74, 72, 13, 10, 40, 12, 58, 76, 52,  5,
       44, 72, 58, 55, 89, 38, 48, 66, 36, 48, 98, 67, 89, 83, 91, 43, 81,
       80, 15, 34, 22, 53, 30, 37, 78, 49, 70, 45, 21, 32, 65, 60, 27, 25,
       98, 20, 83, 32, 19, 45, 59, 67, 41, 66, 40, 97, 79, 85, 92, 50, 85,
       54, 45, 54, 93,  9, 19, 45, 95, 71, 88, 64, 97, 26, 65, 73,  9, 25,
       18, 96, 11, 17, 90, 75, 46, 66, 67, 21, 33, 32, 40, 85, 36, 78, 10,
       66,  2,  6, 31, 35, 23, 60, 91, 46, 97, 73, 59, 74, 26, 14, 40, 59,
       55, 27, 80, 82, 16, 12, 62,  0, 12, 29, 34, 44, 44,  3, 48, 44, 14,
       24, 51, 15, 95, 28, 27, 46, 75, 81, 11, 61, 27, 92, 88, 51, 71, 28,
       93, 67, 56, 36, 59, 35, 65, 71, 47, 54, 31, 20, 98, 49, 41, 38, 43,
       64, 66, 59, 33, 53, 91, 13, 37,  2, 66, 35])

In [40]:
nb_clf = GaussianNB()
nb_clf.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [46]:
y_pred_nb = nb_clf.predict(X_test)
y_pred_nb

array([31, 73,  5,  0, 79, 69, 86, 76, 20, 61, 19, 52, 36, 12, 81, 69, 95,
       54, 52, 11, 17, 26, 92, 70, 74, 72, 13, 10,  2, 26, 58, 76, 69, 78,
       17, 87, 26, 55, 58, 38, 53, 62, 36, 14, 98, 47, 89, 83, 91, 43, 81,
       12, 19, 69, 22, 26, 98, 37, 19, 49, 70, 47, 46, 32, 85, 60, 73, 70,
       98, 93, 41, 69, 19, 47, 78, 47, 85, 77, 36, 97, 79, 85, 92, 50, 85,
       65, 94, 85, 93,  0, 19, 19, 95, 80, 56, 64, 50, 26, 10, 73,  0, 25,
       18, 85, 11, 17, 90, 75, 46, 77, 36, 21, 33, 32, 70, 85, 69, 78, 10,
       69,  2,  6, 70, 16, 70, 92, 91, 50, 91, 19, 26, 74, 26, 11, 69, 80,
       55, 77, 19, 19, 78, 12, 62, 85, 41, 29, 96, 17, 91, 26, 48, 77, 14,
       24, 56, 19, 91, 28, 44, 50, 75, 86, 19, 61, 77, 50, 73, 46, 71, 29,
       93, 67, 26, 85, 82, 16, 65, 71, 47, 85, 31, 26, 98, 49, 26, 28, 43,
       64, 77, 82, 33, 26, 91, 13, 70,  2, 26, 78])

In [51]:
from sklearn.metrics import accuracy_score
print(f'ACCuracy of RandomForest->> {accuracy_score(y_test,y_pred_rf)}')
print(f'ACCuracy of DecisionTree->> {accuracy_score(y_test,y_pred_dt)}')
print(f'ACCuracy of SVM->> {accuracy_score(y_test,y_pred_svm)}')
print(f'ACCuracy of NaiveBaysian->> {accuracy_score(y_test,y_pred_nb)}')

ACCuracy of RandomForest->> 0.9747474747474747
ACCuracy of DecisionTree->> 0.5656565656565656
ACCuracy of SVM->> 0.8838383838383839
ACCuracy of NaiveBaysian->> 0.47474747474747475


-Most accurate model : **RandomForest**

In [62]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred_rf))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         1
           2       1.00      1.00      1.00         2
           5       1.00      1.00      1.00         3
           6       1.00      1.00      1.00         1
           9       1.00      1.00      1.00         3
          10       1.00      1.00      1.00         3
          11       1.00      1.00      1.00         3
          12       1.00      1.00      1.00         1
          13       1.00      1.00      1.00         2
          14       1.00      1.00      1.00         2
          15       1.00      1.00      1.00         2
          16       1.00      1.00      1.00         1
          17       1.00      1.00      1.00         3
          18       1.00      1.00      1.00         1
          19       1.00      1.00      1.00         2
          20       1.00      1.00      1.00         4
          21       1.00      1.00      1.00         2
          22       1.00    

-Random Forest is giving highest accuracy

In [65]:
test_data = pd.read_csv('/content/test.csv')
del test_data['id']
test_data

margin1   margin2   margin3  ...  texture62  texture63  texture64
0    0.019531  0.009766  0.078125  ...   0.000000   0.003906   0.053711
1    0.007812  0.005859  0.064453  ...   0.000977   0.037109   0.044922
2    0.000000  0.000000  0.001953  ...   0.015625   0.000000   0.000000
3    0.000000  0.000000  0.009766  ...   0.089844   0.000000   0.008789
4    0.001953  0.000000  0.015625  ...   0.007812   0.009766   0.007812
..        ...       ...       ...  ...        ...        ...        ...
589  0.000000  0.000000  0.003906  ...   0.018555   0.000000   0.000977
590  0.000000  0.003906  0.003906  ...   0.090820   0.000000   0.016602
591  0.017578  0.029297  0.015625  ...   0.000000   0.042969   0.006836
592  0.013672  0.009766  0.060547  ...   0.000000   0.011719   0.018555
593  0.000000  0.117190  0.000000  ...   0.015625   0.000000   0.017578

[594 rows x 192 columns]

-Result of RandomForest on unseen test data


In [68]:
y_pred_test = rf_clf.predict(test_data)
y_pred_test

array([51, 50,  1, 19, 14,  3,  3, 28, 84,  8, 43, 74, 75, 10, 52, 46, 45,
       73, 13, 71, 61, 68, 57, 77,  1, 70, 28, 15, 35, 70, 53, 74, 47, 50,
        4, 36, 14, 55, 36, 93,  8, 32,  8,  9, 71, 70, 38, 23, 94, 18, 17,
        5, 55, 94, 14, 86, 62, 33, 51, 98, 88, 56, 21, 59, 65, 11, 48,  5,
       13,  4, 54, 57, 29,  7, 31, 98, 92, 84, 25, 10, 61, 43, 85, 24,  1,
        2, 23, 83, 40, 22, 48, 90, 25, 21, 37, 56, 41, 95,  7, 89, 98, 77,
        3, 12, 31, 84, 53, 96, 64, 72, 93, 93, 67, 30,  8, 88, 60, 87,  6,
       57, 34, 90, 60, 17, 64, 27, 51, 31, 39, 23, 29,  2, 41, 61, 24, 97,
       29, 28, 68, 81, 42, 51, 86, 62, 60, 52, 95, 64, 42, 96, 95, 20, 59,
       35, 86,  1, 26, 38, 43, 56, 20, 60, 46, 96, 22, 79, 55, 87, 65, 97,
       64, 21, 29, 21, 11, 10, 58, 94, 27, 22, 15, 45, 89, 54, 43,  5, 23,
       94, 40, 49, 89, 72, 36, 11, 81, 95, 18, 91, 29, 64, 80,  6, 78, 45,
       28,  9, 78, 90, 44, 89, 92, 13,  2, 59,  0, 96, 70, 32, 29, 78, 91,
       55, 44, 38,  5, 60